filebeat.inputs:
  - type: filestream
    id: zeek-cowrie-live-conn-log
    enabled: true
    paths:
      - /usr/share/filebeat/ingest_data/*/conn.log
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          overwrite_keys: true
          expand_keys: true

processors:
  - timestamp:
      field: ts
      layouts:
        - UNIX
      ignore_missing: true
  - dissect:
      tokenizer: "/usr/share/filebeat/ingest_data/%{capture_id}/conn.log"
      field: log.file.path
      target_prefix: ""
      ignore_failure: true
  - add_fields:
      target: ""
      fields:
        source_type: cowrie_live
        sensor_id: zeek-cowrie-live-01
  - add_fields:
      target: event
      fields:
        dataset: zeek.conn
        module: zeek
  - add_tags:
      tags: ["zeek", "conn", "cowrie-live"]

setup.ilm.enabled: false
setup.template.name: zeek-cowrie-live
setup.template.pattern: zeek-cowrie-live-*

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: ["certs/ca/ca.crt"]
  pipeline: "zeek-cowrie-live-enrich-v1"
  index: "zeek-cowrie-live-%{+yyyy.MM.dd}"
